# Generated by Django 3.1.7 on 2021-03-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='image/users', verbose_name='Изображение')),
                ('user_balance', models.FloatField(blank=True, default=0, verbose_name='Баланс')),
            ],
        ),
    ]
