# Generated by Django 3.1.7 on 2021-03-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210305_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to='image/users', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_balance',
            field=models.FloatField(blank=True, default=0, verbose_name='Баланс'),
        ),
    ]
