# Generated by Django 3.1.7 on 2021-03-16 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_course', '0008_auto_20210308_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0016_auto_20210308_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransactionCrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_value', models.FloatField(blank=True, verbose_name='Сума отправителя')),
                ('to_crypt_value', models.FloatField(blank=True, verbose_name='сумма получателя')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_crypt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_course.crypt')),
                ('to_crypt_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_course.cryptowallet')),
            ],
            options={
                'verbose_name': 'Транзакция покупки',
                'verbose_name_plural': 'Транзакции покупки',
            },
        ),
    ]
