# Generated by Django 3.1.7 on 2021-03-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_wallet_transaction_crypt_to_crypt_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_transaction_crypt',
            name='to_crypt_value',
            field=models.FloatField(blank=True, default=1, verbose_name='Сума продажи'),
            preserve_default=False,
        ),
    ]
