# Generated by Django 3.1.7 on 2021-03-08 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_course', '0002_crypt_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypt',
            name='user_login',
        ),
        migrations.AddField(
            model_name='crypt',
            name='user_login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=50, verbose_name='Кошелек')),
                ('value_crypt', models.FloatField(default=0, verbose_name='Сумма')),
                ('crypt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_course.crypt')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
    ]
