# Generated by Django 3.1.7 on 2021-03-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_course', '0003_auto_20210308_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypt',
            old_name='photo',
            new_name='photo_crypt',
        ),
        migrations.RenameField(
            model_name='crypt',
            old_name='user_login',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cryptowallet',
            old_name='crypt_name',
            new_name='name_crypt',
        ),
    ]
