# Generated by Django 3.1.7 on 2021-03-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_course', '0006_auto_20210308_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypt',
            name='wallet',
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='crypt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crypto_course.crypt'),
            preserve_default=False,
        ),
    ]
