# Generated by Django 3.1.7 on 2021-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_course', '0007_auto_20210308_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypt',
            name='symbol_crypt',
            field=models.CharField(max_length=10, verbose_name='Сокращенно'),
        ),
    ]
